# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/volcengine/volcengine-specs.git'
source 'https://github.com/bytedance/cocoapods_sdk_source_repo.git'
# platform :ios, '9.0'

target 'UnityFramework' do
  
  #  TradPlus聚合平台 5.7.3.1
  pod 'TradPlusAdSDK', '5.8.0'
  # Admob 8.5.0
  pod 'TradPlusAdSDK/AdMobAdapter', '5.8.0'
  pod 'Google-Mobile-Ads-SDK','8.9.0'
  # Unity 3.7.1
  pod 'TradPlusAdSDK/UnityAdapter', '5.8.0'
  pod 'UnityAds','3.7.5'
  # Vungle 6.9.2
  pod 'TradPlusAdSDK/VungleAdapter', '5.8.0'
  pod 'VungleSDK-iOS', '6.9.2'
  # 优量汇 4.12.70
  pod 'TradPlusAdSDK/GDTMobAdapter', '5.8.0'
  pod 'GDTMobSDK', '4.12.91'
  # Pangle(穿山甲) 3.6.1.3
  pod 'TradPlusAdSDK/PangleAdapter', '5.8.0'
  pod 'Ads-CN', '3.8.0.2', :subspecs => ['BUAdSDK', 'International']
  
  
  # GA
  pod 'GA-SDK-IOS', '~> 2.2'
  # Adjust
  pod 'Adjust', '~> 4.29.3'
  
  pod 'Firebase/Crashlytics'
  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
  
  # 火山引擎
  pod 'RangersAppLog', '6.0.0',:subspecs => ['Core','Log', 'Host/CN','Unique']
  
  
end


target 'OneSignalNotificationServiceExtension' do
#  only copy below line
  pod 'OneSignal', '>= 3.0.0', '< 4.0'
end
